// generate.mjs — the whole-harness registry generator.
//
// Scans a directory of `*.spec.ts`, each of which `export default`s an
// `agent()` value, and emits ONE `harness.gen.ts` that:
//   1. imports every spec as a typed value,
//   2. folds them into a `Registry` record keyed by file basename,
//   3. emits TYPE-LEVEL cross-checks (dangling-delegate, duplicate-name,
//      cross-file handoff) over the WHOLE registry, so a single `tsc --noEmit`
//      enforces the entire harness as one program.
//
// This is the natural extension of vigiles's existing `generate-types` /
// `generate-schema` codegen (a build/watch step), NOT a runtime import side
// effect. Usage:
//   node generate.mjs <specs-dir> <out-file.ts> [--handoffs a:b,b:c]
//
// `--handoffs a:b` declares a pipeline edge: spec `a`'s `ok` must supply spec
// `b`'s `needs`. (In the real product these edges come from a `pipe()`/railway
// declaration; here we pass them explicitly to exercise the cross-file check.)

import { readdirSync, writeFileSync, readFileSync } from "node:fs";
import { basename, relative, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// The shim lives next to this generator, regardless of where the specs dir is.
const SHIM_PATH = resolve(dirname(fileURLToPath(import.meta.url)), "spec-shim");

const [, , specsDirArg, outFileArg, ...rest] = process.argv;
if (!specsDirArg || !outFileArg) {
  console.error(
    "usage: node generate.mjs <specs-dir> <out-file.ts> [--handoffs a:b,...] [--needs spec:field=type,...]",
  );
  process.exit(1);
}

const specsDir = resolve(specsDirArg);
const outFile = resolve(outFileArg);

// Parse --handoffs a:b,c:d  and  --needs spec:field=type;field=type,...
let handoffs = [];
let needs = {}; // specName -> { field: type }
let dupGuard = true; // JS-side duplicate-name guard (the scalable O(N) path)
for (let i = 0; i < rest.length; i++) {
  if (rest[i] === "--no-dup-guard") {
    // Disable the JS guard so the TYPE-LEVEL duplicate check can be demonstrated.
    dupGuard = false;
  } else if (rest[i] === "--handoffs") {
    handoffs = (rest[++i] ?? "")
      .split(",")
      .filter(Boolean)
      .map((pair) => {
        const [from, to] = pair.split(":");
        return { from, to };
      });
  } else if (rest[i] === "--needs") {
    // spec=field:type|field:type ; spec2=...
    for (const chunk of (rest[++i] ?? "").split(";").filter(Boolean)) {
      const [spec, fields] = chunk.split("=");
      needs[spec] = {};
      for (const f of (fields ?? "").split("|").filter(Boolean)) {
        const [name, type] = f.split(":");
        needs[spec][name] = type;
      }
    }
  }
}

const specFiles = readdirSync(specsDir)
  .filter((f) => f.endsWith(".spec.ts"))
  .sort();

const entries = specFiles.map((f) => {
  const key = basename(f, ".spec.ts"); // registry key (file basename)
  const ident = key.replace(/[^A-Za-z0-9_]/g, "_");
  // Extract the DECLARED `name:` field (a lightweight read — the real product
  // would import the spec; a regex is enough for the prototype's fixtures).
  const src = readFileSync(resolve(specsDir, f), "utf8");
  const m = /name:\s*["'`]([^"'`]+)["'`]/.exec(src);
  const declared = m ? m[1] : key;
  return { file: f, name: key, declared, ident };
});

// DUPLICATE-NAME detection is done HERE, at codegen time, NOT as a type. The
// generator already reads every spec, so a name collision is an O(N) JS check
// with a clean error — far cheaper than the O(N²) injective-name MAPPED TYPE,
// which is exactly the encoding that hits TS2589 around N≈1000 (see perf.mjs).
// It collides on the DECLARED `name:` field, so two files declaring the same
// agent name are caught even though their basenames differ.
if (dupGuard) {
  const seen = new Map();
  for (const e of entries) {
    if (seen.has(e.declared)) {
      console.error(
        `[generate] DUPLICATE agent name "${e.declared}" — ${seen.get(e.declared)} and ${e.file}`,
      );
      process.exit(2);
    }
    seen.set(e.declared, e.file);
  }
}

const outDir = dirname(outFile);
const relImport = (p) => {
  let r = relative(outDir, p).replace(/\\/g, "/");
  if (!r.startsWith(".")) r = "./" + r;
  return r;
};

const lines = [];
lines.push("// AUTO-GENERATED by generate.mjs — DO NOT EDIT.");
lines.push("// One typed registry over every *.spec.ts in the harness, so a");
lines.push(
  "// single `tsc --noEmit` cross-checks the WHOLE harness as one program.",
);
lines.push("");
lines.push(
  `import type { NoDanglingDelegates, Handoff } from ${JSON.stringify(
    relImport(SHIM_PATH),
  )};`,
);
lines.push("");

// Imports
for (const e of entries) {
  lines.push(
    `import ${e.ident} from ${JSON.stringify(relImport(resolve(specsDir, e.file)))};`,
  );
}
lines.push("");

// The registry record. `as const` keeps each value's precise type.
lines.push("export const registry = {");
for (const e of entries) {
  lines.push(`  ${JSON.stringify(e.name)}: ${e.ident},`);
}
lines.push("} as const;");
lines.push("");

// ---- Cross-check 1: dangling delegate -> tsc error ----
lines.push(
  "// CHECK: every delegate target resolves to a real registry entry.",
);
lines.push(
  "// If any agent's `delegatesTo` names a missing spec, `_noDangling`",
);
lines.push(
  "// is NOT `true` and this assignment is a tsc error naming the target.",
);
lines.push("const _noDangling: true = null as unknown as NoDanglingDelegates<");
lines.push("  typeof registry");
lines.push(">;");
lines.push("void _noDangling;");
lines.push("");

// ---- Cross-check 2: duplicate names -> tsc error ----
// Two specs declaring the same `name` field. Because the registry is keyed by
// FILE basename, a duplicate NAME is two distinct keys with the same `__name`.
// We assert each registry key's `__name` equals its key — i.e. file basename ===
// declared name — AND that no two declared names collide. The collision check:
// the union of all `__name`s must have the same cardinality as the keys. We
// encode "names are unique" by requiring each name maps back to exactly one key.
lines.push("// CHECK: declared agent names are unique across the harness.");
lines.push(
  "// `NameOf<K>` is the declared name of entry K; we require the map",
);
lines.push(
  "// name->key to be injective. A duplicate name makes two keys share a",
);
lines.push(
  "// `__name`, so the lookup `KeyForName<dupName>` is a union of >1 key,",
);
lines.push("// which is not assignable to a single key — a tsc error.");
lines.push("type _Reg = typeof registry;");
lines.push('type _NameOf<K extends keyof _Reg> = _Reg[K]["__name"];');
lines.push("type _KeyForName<N extends string> = {");
lines.push("  [K in keyof _Reg]: _NameOf<K> extends N ? K : never;");
lines.push("}[keyof _Reg];");
lines.push(
  "// For every key, the set of keys sharing its name must be just itself.",
);
lines.push("type _NamesUnique = {");
lines.push(
  "  [K in keyof _Reg]: [_KeyForName<_NameOf<K> & string>] extends [K]",
);
lines.push("    ? true");
lines.push(
  "    : { readonly __duplicate_name: _NameOf<K>; readonly keys: _KeyForName<_NameOf<K> & string> };",
);
lines.push("}[keyof _Reg];");
lines.push("const _namesUnique: true = null as unknown as _NamesUnique;");
lines.push("void _namesUnique;");
lines.push("");

// ---- Cross-check 3: cross-file handoffs -> tsc error ----
// For each declared edge from:to with a `needs` shape, the producer's `ok` must
// supply the consumer's needs. We synthesize the consumer needs shape inline.
if (handoffs.length > 0) {
  lines.push(
    "// CHECK: cross-file data handoffs line up (producer.ok ⊇ consumer.needs).",
  );
  handoffs.forEach((h, i) => {
    const consumerNeeds = needs[h.to] ?? {};
    const needsType =
      "{ " +
      Object.entries(consumerNeeds)
        .map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)}`)
        .join("; ") +
      " }";
    lines.push(
      `// edge ${h.from} -> ${h.to}: ${h.from}.ok must supply ${needsType}`,
    );
    lines.push(`const _handoff_${i}: true = null as unknown as Handoff<`);
    lines.push(
      `  NonNullable<typeof registry[${JSON.stringify(h.from)}][\"output\"]>[\"ok\"],`,
    );
    lines.push(`  ${needsType}`);
    lines.push(`>;`);
    lines.push(`void _handoff_${i};`);
  });
  lines.push("");
}

writeFileSync(outFile, lines.join("\n") + "\n");
console.log(
  `[generate] wrote ${relative(process.cwd(), outFile)} over ${entries.length} specs` +
    (handoffs.length ? ` + ${handoffs.length} handoff edge(s)` : ""),
);
