// AUTO-GENERATED by generate.mjs — DO NOT EDIT.
// One typed registry over every *.spec.ts in the harness, so a
// single `tsc --noEmit` cross-checks the WHOLE harness as one program.

import type { NoDanglingDelegates, Handoff } from "./spec-shim";

import implementer from "./specs/implementer.spec.ts";
import planner from "./specs/planner.spec.ts";
import reviewer from "./specs/reviewer.spec.ts";

export const registry = {
  implementer: implementer,
  planner: planner,
  reviewer: reviewer,
} as const;

// CHECK: every delegate target resolves to a real registry entry.
// If any agent's `delegatesTo` names a missing spec, `_noDangling`
// is NOT `true` and this assignment is a tsc error naming the target.
const _noDangling: true = null as unknown as NoDanglingDelegates<
  typeof registry
>;
void _noDangling;

// CHECK: declared agent names are unique across the harness.
// `NameOf<K>` is the declared name of entry K; we require the map
// name->key to be injective. A duplicate name makes two keys share a
// `__name`, so the lookup `KeyForName<dupName>` is a union of >1 key,
// which is not assignable to a single key — a tsc error.
type _Reg = typeof registry;
type _NameOf<K extends keyof _Reg> = _Reg[K]["__name"];
type _KeyForName<N extends string> = {
  [K in keyof _Reg]: _NameOf<K> extends N ? K : never;
}[keyof _Reg];
// For every key, the set of keys sharing its name must be just itself.
type _NamesUnique = {
  [K in keyof _Reg]: [_KeyForName<_NameOf<K> & string>] extends [K]
    ? true
    : {
        readonly __duplicate_name: _NameOf<K>;
        readonly keys: _KeyForName<_NameOf<K> & string>;
      };
}[keyof _Reg];
const _namesUnique: true = null as unknown as _NamesUnique;
void _namesUnique;

// CHECK: cross-file data handoffs line up (producer.ok ⊇ consumer.needs).
// edge planner -> implementer: planner.ok must supply { "plan": "string"; "files": "string[]" }
const _handoff_0: true = null as unknown as Handoff<
  NonNullable<(typeof registry)["planner"]["output"]>["ok"],
  { plan: "string"; files: "string[]" }
>;
void _handoff_0;
