/**
 * vigiles generate-types — emit .d.ts with type unions from actual project state.
 *
 * Scans linter configs, package.json, and filesystem to generate TypeScript
 * types that the compiler uses to PROVE references are valid at authoring time.
 *
 * Generated types:
 *   - EslintRule / StylelintRule / RuffRule / ... — enabled rules per linter
 *   - NpmScript — scripts from package.json
 *   - ProjectFile — files in the project (scoped to src/ by default)
 */

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { globSync } from "glob";
import { LINTERS } from "./linters.js";
import type { DiscoveredRules } from "./linter-adapter.js";

// ---------------------------------------------------------------------------
// NPM script discovery
// ---------------------------------------------------------------------------

function discoverNpmScripts(basePath: string): string[] {
  const pkgPath = resolve(basePath, "package.json");
  if (!existsSync(pkgPath)) return [];
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as {
      scripts?: Record<string, string>;
    };
    return Object.keys(pkg.scripts ?? {});
  } catch {
    return [];
  }
}

// ---------------------------------------------------------------------------
// Project file discovery
// ---------------------------------------------------------------------------

function discoverProjectFiles(
  basePath: string,
  globs: string[] = ["src/**/*"],
): string[] {
  const files: string[] = [];
  for (const pattern of globs) {
    const matches = globSync(pattern, {
      cwd: basePath,
      ignore: ["node_modules/**", "dist/**", ".git/**"],
      nodir: true,
    });
    files.push(...matches);
  }
  return [...new Set(files)].sort();
}

// ---------------------------------------------------------------------------
// Type generation
// ---------------------------------------------------------------------------

function escapeForUnion(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function formatUnion(items: string[], indent: string = "  "): string {
  if (items.length === 0) return "never";
  if (items.length <= 3) {
    return items.map((i) => `"${escapeForUnion(i)}"`).join(" | ");
  }
  return (
    "\n" + items.map((i) => `${indent}| "${escapeForUnion(i)}"`).join("\n")
  );
}

export interface GenerateTypesOptions {
  basePath?: string;
  fileGlobs?: string[];
}

export interface GenerateTypesResult {
  dts: string;
  linters: DiscoveredRules[];
  scripts: string[];
  files: string[];
}

/**
 * Generate .d.ts content with type unions from actual project state.
 *
 * Scans all available linters, package.json scripts, and project files.
 */
export function generateTypes(
  options: GenerateTypesOptions = {},
): GenerateTypesResult {
  const basePath = options.basePath ?? process.cwd();
  const fileGlobs = options.fileGlobs ?? ["src/**/*"];

  // Discover every linter's enabled rules through the single LINTERS registry
  // (each adapter's discoverEnabled) — no separate discoverers list to keep in
  // step with the registry.
  const linters: DiscoveredRules[] = Object.values(LINTERS)
    .map((adapter) => adapter.discoverEnabled?.(basePath))
    .filter((found): found is DiscoveredRules => found != null);

  const scripts = discoverNpmScripts(basePath);
  const files = discoverProjectFiles(basePath, fileGlobs);

  // Generate .d.ts
  const sections: string[] = [];

  sections.push(`/**`);
  sections.push(` * Auto-generated by \`vigiles generate-types\`.`);
  sections.push(
    ` * DO NOT EDIT — re-run \`vigiles generate-types\` to update.`,
  );
  sections.push(` */`);
  sections.push(``);
  // ---------------------------------------------------------------------------
  // vigiles/generated — standalone types for direct import
  // ---------------------------------------------------------------------------

  sections.push(`declare module "vigiles/generated" {`);

  // Linter rules
  for (const { linter, rules, via } of linters) {
    const typeName =
      linter.charAt(0).toUpperCase() +
      linter.slice(1).replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()) +
      "Rule";
    sections.push(``);
    sections.push(
      `  /** ${String(rules.length)} enabled ${linter} rules (via ${via}). */`,
    );
    sections.push(`  export type ${typeName} = ${formatUnion(rules, "    ")};`);
  }

  // Combined linter rule type
  if (linters.length > 0) {
    const allNames = linters.map(
      (l) =>
        l.linter.charAt(0).toUpperCase() +
        l.linter
          .slice(1)
          .replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()) +
        "Rule",
    );
    sections.push(``);
    sections.push(
      `  /** All enabled linter rules across all detected linters. */`,
    );
    sections.push(`  export type LinterRule = ${allNames.join(" | ")};`);
  }

  // NPM scripts
  if (scripts.length > 0) {
    sections.push(``);
    sections.push(
      `  /** ${String(scripts.length)} npm scripts from package.json. */`,
    );
    sections.push(`  export type NpmScript = ${formatUnion(scripts, "    ")};`);
  }

  // Project files
  if (files.length > 0) {
    sections.push(``);
    sections.push(`  /** ${String(files.length)} project files. */`);
    sections.push(`  export type ProjectFile = ${formatUnion(files, "    ")};`);
  }

  sections.push(`}`);

  // ---------------------------------------------------------------------------
  // vigiles/spec augmentation — populates KnownLinterRules, KnownProjectFiles,
  // KnownNpmScripts interfaces so enforce(), file(), cmd() narrow automatically.
  // ---------------------------------------------------------------------------

  sections.push(``);
  sections.push(`declare module "vigiles/spec" {`);

  if (linters.length > 0) {
    sections.push(`  interface KnownLinterRules {`);
    for (const { linter, rules } of linters) {
      sections.push(
        `    "${escapeForUnion(linter)}": ${formatUnion(rules, "      ")};`,
      );
    }
    sections.push(`  }`);
  }

  if (files.length > 0) {
    sections.push(`  interface KnownProjectFiles {`);
    sections.push(`    files: ${formatUnion(files, "      ")};`);
    sections.push(`  }`);
  }

  if (scripts.length > 0) {
    sections.push(`  interface KnownNpmScripts {`);
    sections.push(`    scripts: ${formatUnion(scripts, "      ")};`);
    sections.push(`  }`);
  }

  sections.push(`}`);
  sections.push(``);

  return {
    dts: sections.join("\n"),
    linters,
    scripts,
    files,
  };
}
