/**
 * `vigiles scaffold-test` — the deterministic test-gen engine (B1 v0).
 *
 * Free-form in, a RUNNABLE starter test out. Given an existing hand-written
 * skill / subagent / hook, emit a scaffolded `*.harness.mjs` / `*.eval.mjs` at the
 * surface's suggested test path — the deterministic counterpart to the
 * `test-harness` SKILL (which picks the tier with a model). The scaffold picks the
 * cheapest meaningful tier for the kind, wires the real public API + the surface's
 * own metadata (name, namespaced id, declared tools), and leaves TODOs only where a
 * human/model must supply judgement (the prompts, the event input, the assertion).
 *
 * Pure + model-free: hand it a `ScaffoldInput`, get back a `{ path, content }`. The
 * CLI resolves a surface path / plugin dir into inputs (reusing the scan + untested
 * detectors) and writes the files; this module owns only the templating.
 */
import { dirname } from "node:path";

export type SurfaceKind = "skill" | "agent" | "hook";

/** The cheapest meaningful tier for a surface kind (mirrors the test-harness skill). */
export type TestTier = "unit" | "harness" | "eval";

/** What the generator needs to know about a surface to scaffold its test. */
export interface ScaffoldInput {
  readonly kind: SurfaceKind;
  /** Skill dir name / agent name / hook-script basename. */
  readonly name: string;
  /** Repo-relative path to the surface (SKILL.md / agent .md / hook script). */
  readonly path: string;
  /** Plugin name for the namespaced skill id; a placeholder TODO when unknown. */
  readonly pluginName?: string;
  /** A user-invoked skill — trigger-rate is for model-invocable skills, so note it. */
  readonly userInvoked?: boolean;
  /** A subagent's declared tool contract (drives the assertion hint); null = inherits all. */
  readonly tools?: readonly string[] | null;
  /** How the CLI invokes the hook (e.g. `bash hooks/pre-edit.sh`); a TODO when unknown. */
  readonly hookCommand?: string;
}

export interface Scaffold {
  readonly path: string;
  readonly content: string;
  readonly kind: SurfaceKind;
  readonly tier: TestTier;
}

const PLUGIN_TODO = "<plugin>";

/**
 * The suggested test path for a surface — mirrors `suggestedTestPath` in
 * `test-coverage.ts` (a skill gets an `.eval.mjs`, agent/hook a `.harness.mjs`),
 * so a generated file is colocated where the untested-surface detector looks for it
 * and the surface stops being reported untested.
 */
function suggestedPath(input: ScaffoldInput): string {
  const dir = dirname(input.path);
  const ext = input.kind === "skill" ? "eval.mjs" : "harness.mjs";
  return `${dir}/${input.name}.${ext}`;
}

function header(title: string, run: string): string {
  return [
    "/**",
    ` * ${title}`,
    " *",
    " * Generated by `vigiles scaffold-test` — a STARTER, not a finished test. Fill in",
    " * the TODOs (they're where a human/model must supply judgement), then run:",
    ` *   ${run}`,
    " */",
  ].join("\n");
}

/** A hook → the unit tier (`runHook`): free, no model, reaches every event. */
function hookScaffold(input: ScaffoldInput): string {
  const cmd = input.hookCommand ?? `bash ${input.path}`;
  return `${header(
    `Starter unit test for the \`${input.name}\` hook.`,
    `npx vigiles test ${suggestedPath(input)}`,
  )}
import { runHook, assertHookAllowed } from "vigiles/unit";

// TODO: set the event + input your hook actually inspects (PreToolUse/Bash shown).
const event = {
  hook_event_name: "PreToolUse",
  tool_name: "Bash",
  tool_input: { command: "echo hello" },
};

const r = runHook(${JSON.stringify(cmd)}, event);

// TODO: assert the decision you expect. Use assertHookBlocked(r) for the deny case
// (and a second runHook with the input that SHOULD be blocked).
assertHookAllowed(r);
console.log("✓ ${input.name}: hook allowed the benign event");
`;
}

/** A skill → the eval tier (`measureTriggerRate`): does its description FIRE? */
function skillScaffold(input: ScaffoldInput): string {
  const id = `${input.pluginName ?? PLUGIN_TODO}:${input.name}`;
  const note = input.userInvoked
    ? "\n// NOTE: this skill is user-invoked (disableModelInvocation). Trigger-rate\n// measures MODEL-invocable skills; either make it model-invocable or test its\n// slash-command invocation with runHarnessTest instead.\n"
    : "";
  return `${header(
    `Starter trigger-rate eval for the \`${id}\` skill (recall + precision).`,
    `npx vigiles eval ${suggestedPath(input)}   # real model, on your subscription`,
  )}
import {
  measureTriggerRate,
  formatTriggerRateReport,
  assertTriggerRate,
  skillResolved,
} from "vigiles/testing";
import { fileURLToPath } from "node:url";
${note}
// TODO: point at the plugin root (the dir holding .claude-plugin/ or skills/).
const pluginDir = fileURLToPath(new URL("../../", import.meta.url));
const skill = ${JSON.stringify(id)};

const report = await measureTriggerRate({
  pluginDir,
  stubSkillBodies: true, // firing is a frontmatter property — stub bodies, pay less
  prompts: [
    // TODO: >=5 varied prompts that SHOULD fire ${input.name} (recall).
    "TODO: a realistic task that should trigger ${input.name}",
  ],
  irrelevantPrompts: [
    // TODO: >=5 unrelated prompts that should NOT fire it (precision).
    "TODO: an unrelated coding task",
  ],
  fired: (t) => skillResolved(t, skill),
  trials: Number(process.env.VIGILES_TRIALS || 1),
});

console.log(formatTriggerRateReport(report));
assertTriggerRate(report, { min: 0.8, maxFalsePositive: 0.3 });
`;
}

/** A subagent → the deterministic harness tier; point at the railway/Result path. */
function agentScaffold(input: ScaffoldInput): string {
  const toolHint =
    input.tools && input.tools.length > 0
      ? `assertToolUsed(r, ${JSON.stringify(input.tools[0])}); // its declared contract: ${input.tools.join(", ")}`
      : `assertToolUsed(r, "Task"); // TODO: assert what the subagent should do`;
  return `${header(
    `Starter harness test for the \`${input.name}\` subagent.`,
    `npx vigiles test ${suggestedPath(input)}`,
  )}
import { runHarnessTest, assertToolUsed } from "vigiles/testing";

// A subagent's OUTCOME is best asserted via a result() contract — deterministic,
// no LLM judge. If ${input.name} has one, use assertAgentOk(r.output, contract)
// instead; see the railway-result example in the vigiles docs.

const r = await runHarnessTest({
  plugin: ".", // TODO: the plugin dir holding this subagent
  // TODO: a prompt that dispatches ${input.name} (via the Task tool).
  prompt: "TODO: a task that should dispatch ${input.name}",
  transcript: true,
  model: [{ text: "on it" }],
});

${toolHint}
console.log("✓ ${input.name}: subagent test ran");
`;
}

const TIER: Record<SurfaceKind, TestTier> = {
  hook: "unit",
  skill: "eval",
  agent: "harness",
};

const BUILDER: Record<SurfaceKind, (i: ScaffoldInput) => string> = {
  hook: hookScaffold,
  skill: skillScaffold,
  agent: agentScaffold,
};

/** Scaffold a starter test for one surface. Pure: path + content, no I/O. */
export function scaffoldTest(input: ScaffoldInput): Scaffold {
  return {
    path: suggestedPath(input),
    content: BUILDER[input.kind](input),
    kind: input.kind,
    tier: TIER[input.kind],
  };
}

/** Render a set of scaffolds for the CLI (what was generated, where, which tier). */
export function formatScaffolds(scaffolds: readonly Scaffold[]): string {
  if (scaffolds.length === 0) {
    return "Nothing to scaffold — every surface already has a test, or none was found.";
  }
  const lines = [`Scaffolded ${String(scaffolds.length)} starter test(s):`, ""];
  for (const s of scaffolds) {
    lines.push(`  ${s.path}  [${s.kind} → ${s.tier} tier]`);
  }
  lines.push(
    "",
    "These are STARTERS — fill in the TODOs (prompts / event / assertions), then run",
    "them with `npx vigiles test` (deterministic) or `npx vigiles eval` (real model).",
  );
  return lines.join("\n");
}
